# deploy/k8s/base/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app: api
data:
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_PREFIX: "/api/v1"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  PROJECT_NAME: "Template API"
