# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels:
      - "type:chore"
      - "source:dependabot"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly
    labels:
      - "type:chore"
      - "source:dependabot"
    commit-message:
      prefix: "chore(docker)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "type:chore"
      - "source:dependabot"
    commit-message:
      prefix: "chore(actions)"
