#!/usr/bin/env python3
"""Verify documentation map invariants (see docs/DOCS_MAP.md §0.4)."""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS = REPO_ROOT / "docs"
MAP_PATH = DOCS / "DOCS_MAP.md"
# Regenerated by docs-generator.py; must stay machine-owned for `make docs:check`.
GENERATED_PREFIX = DOCS / "generated"


def _err(msg: str) -> None:
    sys.stderr.write(msg + "\n")


def _parse_frontmatter(raw: str) -> dict[str, str] | None:
    if not raw.startswith("---"):
        return None
    end = raw.find("\n---", 3)
    if end == -1:
        return None
    block = raw[3:end]
    out: dict[str, str] = {}
    for line in block.strip().splitlines():
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip().strip('"')
        out[key] = val
    return out


def _load_doc_ids() -> tuple[dict[str, str], dict[str, str]]:
    """Return (rel_path -> doc_id, doc_id -> rel_path) for all docs except DOCS_MAP."""
    path_to_id: dict[str, str] = {}
    id_to_path: dict[str, str] = {}
    for path in sorted(DOCS.rglob("*.md")):
        rel = path.relative_to(REPO_ROOT).as_posix()
        if rel == "docs/DOCS_MAP.md":
            continue
        try:
            path.relative_to(GENERATED_PREFIX)
        except ValueError:
            pass
        else:
            continue
        text = path.read_text(encoding="utf-8")
        fm = _parse_frontmatter(text)
        if fm is None or "doc_id" not in fm:
            _err(f"error: missing doc_id frontmatter: {rel}")
            sys.exit(1)
        doc_id = fm["doc_id"]
        if doc_id in id_to_path and id_to_path[doc_id] != rel:
            _err(
                f"error: duplicate doc_id {doc_id!r}: {id_to_path[doc_id]} and {rel}",
            )
            sys.exit(1)
        path_to_id[rel] = doc_id
        id_to_path[doc_id] = rel
    return path_to_id, id_to_path


def _parse_map_active_rows(map_text: str) -> dict[str, str]:
    """doc_id -> path from markdown tables under Section 0.2 (active docs only)."""
    if "## 0.3 Retired" in map_text:
        map_text = map_text.split("## 0.3 Retired", 1)[0]
    rows: dict[str, str] = {}
    for line in map_text.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        if line.startswith("|-"):
            continue
        parts = [p.strip() for p in line.strip("|").split("|")]
        if len(parts) < 4:
            continue
        doc_cell = parts[0]
        m = re.fullmatch(r"(\d+\.\d+)", doc_cell.strip())
        if not m:
            continue
        doc_id = m.group(1)
        path_cell = parts[2] if len(parts) > 2 else ""
        bm = re.search(r"`([^`]+)`", path_cell)
        if not bm:
            continue
        path = bm.group(1).strip()
        if not path.startswith("docs/"):
            continue
        if doc_id in rows and rows[doc_id] != path:
            _err(f"error: map lists doc_id {doc_id} twice with different paths")
            sys.exit(1)
        rows[doc_id] = path
    return rows


def _parse_retired_ids(map_text: str) -> set[str]:
    ids: set[str] = set()
    if "## 0.3 Retired" not in map_text:
        return ids
    retired = map_text.split("## 0.3 Retired", 1)[1]
    if "## 0.4" in retired:
        retired = retired.split("## 0.4", 1)[0]
    for line in retired.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        if line.startswith("|-"):
            continue
        parts = [p.strip() for p in line.strip("|").split("|")]
        if len(parts) < 2:
            continue
        cell = parts[0]
        m = re.fullmatch(r"(\d+\.\d+)", cell.strip())
        if m:
            ids.add(m.group(1))
    return ids


def main() -> None:
    if not MAP_PATH.is_file():
        _err("error: docs/DOCS_MAP.md not found")
        sys.exit(1)
    map_text = MAP_PATH.read_text(encoding="utf-8")
    fm_map = _parse_frontmatter(map_text)
    if fm_map is None or fm_map.get("doc_id") != "0":
        _err('error: DOCS_MAP.md must start with frontmatter doc_id: "0"')
        sys.exit(1)

    path_to_id, id_to_path = _load_doc_ids()
    map_rows = _parse_map_active_rows(map_text)
    retired = _parse_retired_ids(map_text)

    for rel, doc_id in path_to_id.items():
        if doc_id not in map_rows:
            _err(f"error: doc_id {doc_id} ({rel}) missing from DOCS_MAP active tables")
            sys.exit(1)
        if map_rows[doc_id] != rel:
            _err(
                "error: path mismatch for "
                f"{doc_id}: file {rel!r} map {map_rows[doc_id]!r}",
            )
            sys.exit(1)

    for doc_id, rel in map_rows.items():
        if doc_id in retired:
            _err(f"error: doc_id {doc_id} appears in active map and retired table")
            sys.exit(1)
        if rel not in path_to_id:
            _err(f"error: map references missing file {rel}")
            sys.exit(1)
        if path_to_id[rel] != doc_id:
            _err(
                "error: map doc_id "
                f"{doc_id} does not match file frontmatter for {rel} ({path_to_id[rel]})",
            )
            sys.exit(1)

    if set(map_rows.keys()) != set(path_to_id.values()):
        only_map = set(map_rows.keys()) - set(path_to_id.values())
        only_files = set(path_to_id.values()) - set(map_rows.keys())
        if only_map:
            extra = sorted(only_map)
            _err(f"error: map has extra doc_ids not in files: {extra}")
        if only_files:
            missing = sorted(only_files)
            _err(f"error: files have doc_ids not in map: {missing}")
        sys.exit(1)

    for rid in retired:
        if rid in id_to_path:
            _err(f"error: retired doc_id {rid} still present as a file")
            sys.exit(1)

    sys.stdout.write("check_docs_map: OK — all invariants satisfied\n")
    sys.stdout.write(f"  indexed docs: {len(path_to_id)}\n")


if __name__ == "__main__":
    main()
