#!/usr/bin/env bash
# scripts/codebase-summary.sh
# Fully regenerate CODEBASE_SUMMARY.md (counts and entry points).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

python3 <<'PY'
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

root = Path(".")

modules = sorted(p.stem for p in root.glob("apps/api/app/api/routes/*.py") if p.stem != "__init__")
packages = sorted(p.parent.name for p in root.glob("packages/*/AGENTS.md"))
skills = sorted(
    str(p.relative_to(root))
    for p in root.glob("skills/**/*.md")
    if p.name != "README.md"
)
prompts = sorted(p.name for p in root.glob("prompts/*.md") if p.name != "README.md")
scripts = sorted(p.name for p in root.glob("scripts/*.sh"))
procedures = sorted(
    p.name for p in root.glob("docs/procedures/*.md") if p.name != "README.md"
)

q = root / "queue" / "queue.csv"
q_lines = [ln for ln in q.read_text(encoding="utf-8").splitlines() if ln.strip() and not ln.startswith("#")]
queue_count = max(0, len(q_lines) - 1)

now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

mod_lines = "\n".join(f"- `apps/api/app/api/routes/{m}.py`" for m in modules) or "- _(none yet)_"
pkg_lines = "\n".join(f"- `packages/{p}/`" for p in packages) or "- _(none yet)_"

summary = f"""# CODEBASE_SUMMARY.md
<!-- Auto-generated by make codebase-summary — do not edit manually -->
<!-- Generated: {now} -->

## Stack
- Backend: Python 3.12+, FastAPI, SQLModel, Postgres, Alembic, Pydantic v2, pytest
- Frontend: React 19, Vite, TanStack Router/Query, Tailwind v4, shadcn/ui, Playwright
- Orchestration: Docker Compose (db + adminer + backend + frontend + prestart), Traefik overlay

## API routes
{mod_lines}

## Packages
{pkg_lines}

## Queue
- Open items: {queue_count}
- Files: `queue/queue.csv`, `queue/queuearchive.csv`

## Counts
- Skills: {len(skills)}
- Prompts: {len(prompts)}
- Shell scripts: {len(scripts)}
- Procedures: {len(procedures)}

## Key entry points
- API:       `apps/api/app/main.py`
- Config:    `apps/api/app/core/config.py`
- Models:    `apps/api/app/models.py`
- Frontend:  `apps/web/src/main.tsx`
- Compose:   `compose.yml` + `compose.override.yml`
- AGENTS: `AGENTS.md`
- Agent control: `AGENTS.md` (root) + `apps/api/AGENTS.md` + `apps/web/AGENTS.md`
- Python rules: `docs/development/python-procedures.md`
- Commands: `make help`
"""
Path("docs/generated/CODEBASE_SUMMARY.md").write_text(summary, encoding="utf-8")
print("Regenerated docs/generated/CODEBASE_SUMMARY.md")
PY
