#!/usr/bin/env bash
# scripts/codebase-summary.sh
# Fully regenerate CODEBASE_SUMMARY.md (counts and entry points).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

python3 <<'PY'
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

root = Path(".")

modules = sorted(p.parent.name for p in root.glob("apps/api/src/*/router.py"))
packages = sorted(p.parent.name for p in root.glob("packages/*/AGENTS.md"))
skills = sorted(
    str(p.relative_to(root))
    for p in root.glob("skills/**/*.md")
    if p.name != "README.md"
)
prompts = sorted(p.name for p in root.glob("prompts/*.md") if p.name != "README.md")
scripts = sorted(p.name for p in root.glob("scripts/*.sh"))
procedures = sorted(
    p.name for p in root.glob("docs/procedures/*.md") if p.name != "README.md"
)

q = root / "queue" / "queue.csv"
q_lines = [ln for ln in q.read_text(encoding="utf-8").splitlines() if ln.strip() and not ln.startswith("#")]
queue_count = max(0, len(q_lines) - 1)

now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

mod_lines = "\n".join(f"- `apps/api/src/{m}/`" for m in modules) or "- _(none yet)_"
pkg_lines = "\n".join(f"- `packages/{p}/`" for p in packages) or "- _(none yet)_"

summary = f"""# CODEBASE_SUMMARY.md
<!-- Auto-generated by make codebase-summary — do not edit manually -->
<!-- Generated: {now} -->

## Stack
Python 3.12+, FastAPI, SQLAlchemy (async), Alembic, Pydantic v2, pytest

## API modules
{mod_lines}

## Packages
{pkg_lines}

## Queue
- Open items: {queue_count}
- Files: `queue/queue.csv`, `queue/queuearchive.csv`

## Counts
- Skills: {len(skills)}
- Prompts: {len(prompts)}
- Shell scripts: {len(scripts)}
- Procedures: {len(procedures)}

## Key entry points
- API: `apps/api/src/main.py`
- Config: `apps/api/src/config.py`
- Spec: `spec/spec.md`
- Agent control: `AGENTS.md`
- Python rules: `PYTHON_PROCEDURES.md`
- Commands: `make help`
"""
Path("CODEBASE_SUMMARY.md").write_text(summary, encoding="utf-8")
print("Regenerated CODEBASE_SUMMARY.md")
PY
